sonar.projectKey=crgolden_Manuals
sonar.organization=crgolden

sonar.sources=Manuals
sonar.tests=Manuals.Tests
sonar.exclusions=**/bin/**,**/obj/**

sonar.cs.vscoveragexml.reportsPaths=coverage.xml,coverage-integration.xml
